// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Tue, 30 Aug 2016 02:26:20 MSK.
// By http://git.io/cgogen. DO NOT EDIT.

#include "z_libpd.h"
#include <stdlib.h>
#pragma once

#define __CGOGEN 1

// t_libpd_printhook_e41f15cd is a proxy for callback t_libpd_printhook.
void t_libpd_printhook_e41f15cd(char* recv);

// t_libpd_banghook_7ee06eb6 is a proxy for callback t_libpd_banghook.
void t_libpd_banghook_7ee06eb6(char* recv);

// t_libpd_floathook_c0728ac0 is a proxy for callback t_libpd_floathook.
void t_libpd_floathook_c0728ac0(char* recv, float x);

// t_libpd_symbolhook_a2f11e30 is a proxy for callback t_libpd_symbolhook.
void t_libpd_symbolhook_a2f11e30(char* recv, char* sym);

// t_libpd_listhook_c08dcef4 is a proxy for callback t_libpd_listhook.
void t_libpd_listhook_c08dcef4(char* recv, int argc, t_atom* argv);

// t_libpd_messagehook_cb0280 is a proxy for callback t_libpd_messagehook.
void t_libpd_messagehook_cb0280(char* recv, char* msg, int argc, t_atom* argv);

// t_libpd_noteonhook_73e8687d is a proxy for callback t_libpd_noteonhook.
void t_libpd_noteonhook_73e8687d(int channel, int pitch, int velocity);

// t_libpd_controlchangehook_7248f877 is a proxy for callback t_libpd_controlchangehook.
void t_libpd_controlchangehook_7248f877(int channel, int controller, int value);

// t_libpd_programchangehook_527988c8 is a proxy for callback t_libpd_programchangehook.
void t_libpd_programchangehook_527988c8(int channel, int value);

// t_libpd_pitchbendhook_8bf1c1f3 is a proxy for callback t_libpd_pitchbendhook.
void t_libpd_pitchbendhook_8bf1c1f3(int channel, int value);

// t_libpd_aftertouchhook_e7d4f475 is a proxy for callback t_libpd_aftertouchhook.
void t_libpd_aftertouchhook_e7d4f475(int channel, int value);

// t_libpd_polyaftertouchhook_c3cfeaf7 is a proxy for callback t_libpd_polyaftertouchhook.
void t_libpd_polyaftertouchhook_c3cfeaf7(int channel, int pitch, int value);

// t_libpd_midibytehook_6393d784 is a proxy for callback t_libpd_midibytehook.
void t_libpd_midibytehook_6393d784(int port, int byte);

