// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Sat, 27 Aug 2016 22:58:56 MSK.
// By http://git.io/cgogen. DO NOT EDIT.

/*
Package core provides Go bindings for libpd — Pure Data embeddable audio synthesis library.
*/
package core
