// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Fri, 19 Aug 2016 23:55:07 MSK.
// By http://git.io/cgogen. DO NOT EDIT.

/*
Package core provides Go bindings for libpd — Pure Data embeddable audio synthesis library.
*/
package core
