// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Sun, 04 Sep 2016 02:38:44 MSK.
// By http://git.io/cgogen. DO NOT EDIT.

/*
Package core provides Go bindings for libpd — Pure Data embeddable audio synthesis library.
*/
package core
