// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Thu, 22 Sep 2016 23:18:48 MSK.
// By https://git.io/cgogen. DO NOT EDIT.

package core

/*
#cgo LDFLAGS: -lpd
#include "z_libpd.h"
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"

// PrintHook type as declared in core/z_libpd.h:69
type PrintHook func(recv string)

// BangHook type as declared in core/z_libpd.h:70
type BangHook func(recv string)

// FloatHook type as declared in core/z_libpd.h:71
type FloatHook func(recv string, x float32)

// SymbolHook type as declared in core/z_libpd.h:72
type SymbolHook func(recv string, sym string)

// ListHook type as declared in core/z_libpd.h:73
type ListHook func(recv string, argc int32, argv *Atom)

// MessageHook type as declared in core/z_libpd.h:74
type MessageHook func(recv string, msg string, argc int32, argv *Atom)

// NoteOnHook type as declared in core/z_libpd.h:94
type NoteOnHook func(channel int32, pitch int32, velocity int32)

// ControlChangeHook type as declared in core/z_libpd.h:95
type ControlChangeHook func(channel int32, controller int32, value int32)

// ProgramChangeHook type as declared in core/z_libpd.h:97
type ProgramChangeHook func(channel int32, value int32)

// PitchbendHook type as declared in core/z_libpd.h:98
type PitchbendHook func(channel int32, value int32)

// AftertouchHook type as declared in core/z_libpd.h:99
type AftertouchHook func(channel int32, value int32)

// PolyAftertouchHook type as declared in core/z_libpd.h:100
type PolyAftertouchHook func(channel int32, pitch int32, value int32)

// MIDIByteHook type as declared in core/z_libpd.h:101
type MIDIByteHook func(port int32, byte int32)

// PdInstance as declared in core/m_pd.h:796
type PdInstance C.struct__pdinstance
